task: sa
cuda_id: 1
seed: 42

wandb_dir: /home/user/repo/VLSA
wandb_prj: VLSA-IFMLE
save_path: ./result/exp-ifmle/{0}-abmil-baseline-CONCH
save_prediction: True
eval_training_loader_per_epoch: False
ckpt_for_eval: last # last / best
num_shot: [-1] # active if num_shot >= 0

# data loading
dataset_name: ['tcga_blca']
path_patch: /{1}/ExpData/{0}/tiles-20x-s448/feats-CONCH/pt_files # X / X-vl-proj
path_coord: /{1}/ExpData/{0}/tiles-20x-s448/patches
path_table: ./data_split/5foldcv/{0}/mahmoodlab_{0}_survival.csv
data_mode: patch
path_cluster: null
path_graph: null
feat_format: pt
time_format: interval # 'origin', 'ratio', 'quantile', 'interval'
time_bins: null # sqrt(num_events), automatically filled
data_split_path: ./data_split/5foldcv/{0}/splits_{2}.csv
data_split_seed: [0, 1, 2, 3, 4]

# network architecture
arch: DeepMIL # DeepMIL / VLSA
net_dims: 512-256-0 # 512-256-X (VL space or Vis space) for CONCH
init_wt: False
net_output_converter: softmax # use to convert prediction

# DeepMIL setttings
deepmil_network: ABMIL
deepmil_use_feat_proj: False
deepmil_drop_rate: 0.25
deepmil_pooling: attention # only for DeepMIL, max / mean / attention / gated_attention

# training loss
loss_type: SurvIFMLE # use XXX-XXX-XXX to configure multi-loss
loss_survifmle_weight: 1.0

# evaluator
evaluator: NLL-IF # Reg / NLL / Cox / VL

# optimizer
opt_name: adam
opt_lr: 0.0002
opt_weight_decay: 0.00001

#training
epochs: 10 # 
batch_size: 1
bp_every_batch: 32
num_workers: 4

# Early Stopping
es: False
es_patience: 20
es_warmup: 0
es_verbose: True
es_start_epoch: 0
monitor_metrics: loss # loss / c_index

# LR Scheduler
lrs: False
lrs_factor: 0.5
lrs_patience: 10

# In a test mode
test: False